[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = false
build_info = true
extra_output = ["storageLayout", "evm.bytecode.generatedSources"]
bytecode_hash = "ipfs"
cbor_metadata = true
cache = false
solc_version = "0.8.24"
